import React from "react";
import { BookOpenCheck, CheckCircle2, FileText, ListChecks } from "lucide-react";

export const ProductPreview: React.FC = () => (
  <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 sm:pb-24 lg:px-8">
    <div className="grid items-center gap-10 rounded-[var(--radius-card)] border border-[var(--line)] bg-[var(--paper)] p-6 sm:p-10 lg:grid-cols-[0.85fr_1.15fr] lg:gap-14 lg:p-12">
      <div><span className="inline-flex rounded-[var(--radius-pill)] bg-[var(--sage)] px-3 py-1 text-xs font-extrabold tracking-wider text-[var(--ink)]">VEJA A ORGANIZAÇÃO</span><h2 className="mt-5 text-balance text-3xl font-extrabold tracking-tight text-[var(--ink)] sm:text-4xl">O que você encontra quando abre um tema.</h2><p className="mt-5 max-w-xl text-base font-medium leading-relaxed text-[var(--ink-soft)] sm:text-lg">A amostra mostra como os materiais ficam reunidos: um tema, os resumos de apoio, pontos-chave e questões para revisar sem abrir dezenas de arquivos.</p><a href="https://locusmed.pages.dev/" target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex min-h-11 items-center rounded-[var(--radius-lg)] bg-[var(--yellow)] px-5 text-sm font-extrabold text-[var(--ink)] shadow-sm hover:bg-[var(--yellow-deep)]">Abrir a amostra e ver o material</a></div>
      <div className="rounded-[var(--radius-md)] border border-[var(--line)] bg-[var(--surface)] p-4 shadow-[var(--shadow-soft)] sm:p-5"><div className="flex items-center justify-between border-b border-[var(--line)] pb-4"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-[var(--radius-icon)] bg-[var(--lav)]"><BookOpenCheck className="h-5 w-5" aria-hidden="true" /></span><div><p className="text-sm font-extrabold text-[var(--ink)]">Tema de estudo</p><p className="text-xs font-medium text-[var(--muted)]">Material organizado em um só lugar</p></div></div><span className="rounded-[var(--radius-pill)] bg-[var(--paper)] px-2.5 py-1 text-[11px] font-extrabold text-[var(--info-accent)]">AMOSTRA</span></div><div className="mt-4 grid gap-3 sm:grid-cols-[0.9fr_1.1fr]"><div className="space-y-2"><p className="px-2 text-xs font-extrabold tracking-wide text-[var(--muted)]">NESTE TEMA</p>{["Resumo principal", "Pontos-chave", "Questões para revisar"].map((item, index) => <div key={item} className={`flex items-center gap-2 rounded-[var(--radius-control)] px-3 py-2.5 text-xs font-bold ${index === 0 ? "bg-[var(--yellow)] text-[var(--ink)]" : "bg-[var(--paper)] text-[var(--ink-soft)]"}`}><FileText className="h-3.5 w-3.5" aria-hidden="true" />{item}</div>)}</div><div className="rounded-[var(--radius-control)] bg-[var(--paper)] p-4"><p className="text-xs font-extrabold tracking-wide text-[var(--info-accent)]">PONTOS-CHAVE</p><h3 className="mt-2 text-lg font-extrabold tracking-tight text-[var(--ink)]">Revisão direta, por assunto.</h3><div className="mt-4 space-y-2.5">{["Conteúdo separado por tema", "Leitura com foco no essencial", "Questões para testar a fixação"].map((item) => <p key={item} className="flex items-start gap-2 text-xs font-medium leading-relaxed text-[var(--ink-soft)]"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[var(--success-accent)]" aria-hidden="true" />{item}</p>)}</div><div className="mt-4 flex items-center gap-2 border-t border-[var(--line)] pt-3 text-xs font-extrabold text-[var(--ink)]"><ListChecks className="h-4 w-4 text-[var(--info-accent)]" aria-hidden="true" />Revise, marque e siga para o próximo tema</div></div></div></div>
    </div>
  </section>
);
